### ISSUE TITLE
Some layout error

### ISSUE THREAD

**Issue by NoverNobida** [Dabsunter/ayourls#1]
1. The addlink dialog is too narrow;
2. The QRcode is too big;
3. The description of url is not center alignment.
![Screenshot_aYourls_20200628-231949](https://user-images.githubusercontent.com/46912250/85951485-13676e80-b996-11ea-8a14-b620e6b6ecf0.png)

**Comment by Dabsunter** [comment]
Hello, this project is from @matecode as you can see in the first commits and it was hosted on Gitlab.

My repository is mirrored here https://gitlab.com/Dabsunter/ayourls and you can see that it's a fork of https://gitlab.com/RubenFixit/ayourls which is also a fork of the original https://gitlab.com/matecode/ayourls

Ruben fixed some issues related to the new version of Android, and I altered the URL verification mechanism for my own usage and added the French language (see my commits).

I've done that for my own usage, and you are free to use it or even open a pull request, but I didn't have in mind to be the new maintainer of this project 😉

**Comment by NoverNobida** [comment]
So many forks😄.
I continue to use it. Because I don't know how to develop on Android, I just built an apk to use.
